<a href="https://colab.research.google.com/github/KarinaSelingardi/ESTUDOS-DE-PYTHON/blob/main/jacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

def gauss_jacobi(A, b, x0, tol, max_iter):
    n = len(b)
    x = x0.copy()
    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            sum_ax = np.dot(A[i, :i], x_old[:i]) + np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - sum_ax) / A[i, i]

        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            print(f"Convergiu em {k+1} iterações.")
            return x

    print("Não convergiu no número máximo de iterações.")
    return x

# Exemplo de uso:
A = np.array([[10.0, -1.0, 2.0], [1.0, 11.0, -1.0],[2.0,-1.0,10.0]])
b = np.array([6.0, 25.0, -11.0])
x0 = np.array([0.0, 0.0, 0.0])

tol=1 & -5 #tolerancia
max_iter=20

solucao_jacobi = gauss_jacobi(A, b, x0,tol,max_iter)
print("Solução (Jacobi):", solucao_jacobi)


Convergiu em 2 iterações.
Solução (Jacobi): [ 1.04727273  2.11818182 -0.99272727]


### **Projeto: Resolução de Sistemas Lineares com o Método de Jacobi**

Este projeto demonstra a aplicação do método iterativo de Jacobi para resolver um sistema de equações lineares da forma $Ax = b$.

#### **1. Definição do Sistema de Equações**

Vamos definir um novo sistema $Ax = b$ para resolver. Para garantir que o método de Jacobi convirja, é ideal que a matriz $A$ seja diagonalmente dominante.

In [5]:
# Defina a matriz A e o vetor b para um novo sistema
# Este é um exemplo de matriz diagonalmente dominante, o que ajuda na convergência do método de Jacobi
A_projeto = np.array([
    [4.0, -1.0, 1.0],
    [1.0, 5.0, 2.0],
    [0.0, 1.0, 3.0]
])
b_projeto = np.array([8.0, 15.0, 10.0])
x0_projeto = np.array([0.0, 0.0, 0.0]) # Estimativa inicial

print("Matriz A do projeto:")
print(A_projeto)
print("Vetor b do projeto:")
print(b_projeto)

Matriz A do projeto:
[[ 4. -1.  1.]
 [ 1.  5.  2.]
 [ 0.  1.  3.]]
Vetor b do projeto:
[ 8. 15. 10.]


#### **2. Aplicação do Método de Jacobi**

Agora vamos usar a função `gauss_jacobi` que definimos para resolver este novo sistema. Vamos aumentar o número máximo de iterações e refinar a tolerância para observar a convergência.

In [6]:
# Parâmetros para o método de Jacobi
tol_projeto = 1e-6       # Tolerância para a convergência
max_iter_projeto = 1000  # Número máximo de iterações

# Chama a função gauss_jacobi
solucao_jacobi_projeto = gauss_jacobi(A_projeto, b_projeto, x0_projeto, tol_projeto, max_iter_projeto)

print("\nSolução encontrada pelo Método de Jacobi:", solucao_jacobi_projeto)

Convergiu em 16 iterações.

Solução encontrada pelo Método de Jacobi: [1.67857144 1.53571406 2.82142836]


#### **3. Verificação da Solução**

Podemos verificar a precisão da solução do método de Jacobi comparando-a com uma solução obtida por um método direto, como o `np.linalg.solve` do NumPy.

In [7]:
# Solução exata usando np.linalg.solve para comparação
solucao_exata = np.linalg.solve(A_projeto, b_projeto)

print("Solução exata (np.linalg.solve):", solucao_exata)

# Comparar as soluções
erro = np.linalg.norm(solucao_jacobi_projeto - solucao_exata)
print(f"\nErro (norma da diferença): {erro:.2e}")

if erro < tol_projeto * 10: # Multiplicado por 10 para uma verificação mais flexível
    print("As soluções são muito próximas, indicando que o método de Jacobi convergiu corretamente.")
else:
    print("As soluções diferem mais do que o esperado. Pode ser necessário ajustar a tolerância ou o número de iterações.")

Solução exata (np.linalg.solve): [1.67857143 1.53571429 2.82142857]

Erro (norma da diferença): 3.09e-07
As soluções são muito próximas, indicando que o método de Jacobi convergiu corretamente.
