<a href="https://colab.research.google.com/github/KarinaSelingardi/ESTUDOS-DE-PYTHON/blob/main/matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Matriz A e vetor b
A = np.array([[2, 1, 1],
              [4, 3, 3],
              [6, 5, 4]], dtype=float)

b = np.array([5, 11, 17], dtype=float)

# Inicializa L como identidade e U como zeros

# Decomposição LU (sem pivoteamento)
def decomposicaoLU(A,b):
  n = len(A)
  L = np.eye(n)
  U = np.zeros((n, n))
  for i in range(n):
      for j in range(i, n):
          total = 0.0
          for k in range(i):
              total += L[i][k] * U[k][j]
          U[i][j] = A[i][j] - total
      for j in range(i+1, n):
          total = 0.0
          for k in range(i):
              total += L[j][k] * U[k][i]
          L[j][i] = (A[j][i] - total) / U[i][i]

  # Resolver L·y = b (substituição direta)
  y = np.zeros(n)
  for i in range(n):
      total = 0.0
      for j in range(i):
          total += L[i][j] * y[j]
      y[i] = b[i] - total

  # Resolver U·x = y (substituição retroativa)
  x = np.zeros(n)
  for i in range(n-1, -1, -1):
      total = 0.0
      for j in range(i+1, n):
          total += U[i][j] * x[j]
      x[i] = (y[i] - total) / U[i][i]
  return x
# Resultado
x = decomposicaoLU(A,b)
print("Solução do sistema A·x = b:")
print(x)


Solução do sistema A·x = b:
[ 2.  1. -0.]


In [ ]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

def resolver_sistema_lu_scipy_simples(A, b):
    """
    Resolve um sistema linear Ax = b usando decomposição LU com
    SciPy.
    Esta é uma versão simplificada que foca os passos principais.

    Args:
        A (np.ndarray): Matriz de coeficientes.
        b (np.ndarray): Vetor de termos independentes.

    Returns:
        np.ndarray: Vetor solução x.

    """
    # 1. Realizar a decomposição LU com pivotação (PA = LU)
    # lu_factor retorna uma tupla (lu_matrix, pivot_indices)
    lu, piv = lu_factor(A)

    # 2. Resolver o sistema usando os fatores LU e os pivôs
    # lu_solve resolve Ly = Pb e depois Ux = y
    x = lu_solve((lu, piv), b)

    return x

A = np.array([[2, 1, 1],
              [4, 3, 3],
              [6, 5, 4]], dtype=float)

b = np.array([5, 11, 17], dtype=float)

print("Matriz A:\n", A)
print("Vetor b:\n", b)
solucao_x = resolver_sistema_lu_scipy_simples(A, b)
print("\nSolução x (via LU com SciPy):")
print(solucao_x)


Matriz A:
 [[2. 1. 1.]
 [4. 3. 3.]
 [6. 5. 4.]]
Vetor b:
 [ 5. 11. 17.]

Solução x (via LU com SciPy):
[2.00000000e+00 1.00000000e+00 1.44328993e-15]


In [ ]:
import numpy as np
A=np.array([[2.,-1.,0.],[-1.,2.,-1.],[0.,-1.,2.]])
b=np.array([1.,0,0])
def metodo_iterativo(A,b,x0,kmax):
  #M= identidade
   for k in range(kmax):
      r = b - A@x0
      p = r


      x0 += p
   return x0, k
x0=np.zeros(3)
kmax=3
x,k = metodo_iterativo(A,b,x0,kmax)
print('x=',x)
print('k=',k)

x= [ 2. -1.  1.]
k= 2


### Execução Manual do Método Iterativo

**Dados iniciais:**
*   Matriz `A`:
    ```
    [[ 2., -1.,  0.],
     [-1.,  2., -1.],
     [ 0., -1.,  2.]]
    ```
*   Vetor `b`:
    ```
    [1., 0., 0.]
    ```
*   Estimativa inicial `x0`:
    ```
    [0., 0., 0.]
    ```
*   Número máximo de iterações `kmax = 3`

---

### **Iteração 1 (k = 0)**

1.  **Calcular o resíduo `r = b - A @ x0`:**

    *   `A @ x0`:
        ```
        [[ 2., -1.,  0.],
         [-1.,  2., -1.],
         [ 0., -1.,  2.]] @ [0., 0., 0.]  =  [0., 0., 0.]
        ```
    *   `r = [1., 0., 0.] - [0., 0., 0.]  =  [1., 0., 0.]`

2.  **Definir `p = r`:**

    *   `p = [1., 0., 0.]`

3.  **Atualizar `x0 = x0 + p`:**

    *   `x0 = [0., 0., 0.] + [1., 0., 0.]  =  [1., 0., 0.]`

**Resultado da Iteração 1: `x0 = [1., 0., 0.]`**

---

### **Iteração 2 (k = 1)**

1.  **Calcular o resíduo `r = b - A @ x0` (usando o `x0` da iteração anterior):**

    *   `A @ x0`:
        ```
        [[ 2., -1.,  0.],
         [-1.,  2., -1.],
         [ 0., -1.,  2.]] @ [1., 0., 0.]  =  [ (2*1 + (-1)*0 + 0*0),  ((-1)*1 + 2*0 + (-1)*0),  (0*1 + (-1)*0 + 2*0) ]
                                      =  [ 2., -1.,  0. ]
        ```
    *   `r = [1., 0., 0.] - [2., -1., 0.]  =  [-1., 1., 0.]`

2.  **Definir `p = r`:**

    *   `p = [-1., 1., 0.]`

3.  **Atualizar `x0 = x0 + p`:**

    *   `x0 = [1., 0., 0.] + [-1., 1., 0.]  =  [0., 1., 0.]`

**Resultado da Iteração 2: `x0 = [0., 1., 0.]`**

---

### **Iteração 3 (k = 2)**

1.  **Calcular o resíduo `r = b - A @ x0` (usando o `x0` da iteração anterior):**

    *   `A @ x0`:
        ```
        [[ 2., -1.,  0.],
         [-1.,  2., -1.],
         [ 0., -1.,  2.]] @ [0., 1., 0.]  =  [ (2*0 + (-1)*1 + 0*0),  ((-1)*0 + 2*1 + (-1)*0),  (0*0 + (-1)*1 + 2*0) ]
                                      =  [-1.,  2., -1.]
        ```
    *   `r = [1., 0., 0.] - [-1., 2., -1.]  =  [2., -2., 1.]`

2.  **Definir `p = r`:**

    *   `p = [2., -2., 1.]`

3.  **Atualizar `x0 = x0 + p`:**

    *   `x0 = [0., 1., 0.] + [2., -2., 1.]  =  [2., -1., 1.]`

**Resultado da Iteração 3: `x0 = [2., -1., 1.]`**

---

**Este resultado `[2., -1., 1.]` corresponde exatamente ao que foi obtido pela execução da função `metodo_iterativo` na célula original.**